// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbVjr0cWcmhwA04N_8AYJg2v1Sfwjihw',
    appId: '1:84285132119:web:4b6335f13de937814f8212',
    messagingSenderId: '84285132119',
    projectId: 'twitterclonetute-546b0',
    authDomain: 'twitterclonetute-546b0.firebaseapp.com',
    storageBucket: 'twitterclonetute-546b0.appspot.com',
    measurementId: 'G-BC8X1E97LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPK-vQ2Z14E_osZldz2iHYeGSjV2ngcoY',
    appId: '1:84285132119:android:d5307bbeee228fef4f8212',
    messagingSenderId: '84285132119',
    projectId: 'twitterclonetute-546b0',
    storageBucket: 'twitterclonetute-546b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3F5PVw29s9auvyPtWA9eTBnsVu9P4Itc',
    appId: '1:84285132119:ios:7b8214207a18aa8d4f8212',
    messagingSenderId: '84285132119',
    projectId: 'twitterclonetute-546b0',
    storageBucket: 'twitterclonetute-546b0.appspot.com',
    iosBundleId: 'com.example.flutterTwitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3F5PVw29s9auvyPtWA9eTBnsVu9P4Itc',
    appId: '1:84285132119:ios:7b8214207a18aa8d4f8212',
    messagingSenderId: '84285132119',
    projectId: 'twitterclonetute-546b0',
    storageBucket: 'twitterclonetute-546b0.appspot.com',
    iosBundleId: 'com.example.flutterTwitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjbVjr0cWcmhwA04N_8AYJg2v1Sfwjihw',
    appId: '1:84285132119:web:123446023cfe25704f8212',
    messagingSenderId: '84285132119',
    projectId: 'twitterclonetute-546b0',
    authDomain: 'twitterclonetute-546b0.firebaseapp.com',
    storageBucket: 'twitterclonetute-546b0.appspot.com',
    measurementId: 'G-ZYD2CVGNDE',
  );
}